version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
    staticcheck:
      checks:
        - "all"
        - "-ST1000"  # Package comments
        - "-ST1001"  # Dot imports (used in test files with ginkgo/gomega)
        - "-ST1003"  # Naming conventions (Api vs API)

formatters:
  enable:
    - gofmt
    - goimports
