version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: "api/*"
      linters:
        - dupl
    - path: "internal/*"
      linters:
        - dupl
    # Allow dot imports in test files (ginkgo/gomega convention)
    - path: "_test\\.go$"
      text: "ST1001"
    - path: "test/"
      text: "ST1001"

linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
    staticcheck:
      checks:
        - "all"
        - "-ST1000"  # Package comments
        - "-ST1001"  # Dot imports (used in test files with ginkgo/gomega)
        - "-ST1003"  # Naming conventions (Api vs API)

formatters:
  enable:
    - gofmt
    - goimports
