---
branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: make build-installer IMG=ghcr.io/joelp172/uptime-robot-operator:v${nextRelease.version}
  - - "@semantic-release/github"
    - assets:
        - path: dist/install.yaml
          label: Kubernetes Installation Manifest
