// Code generated by "enumer -type AssertionOperator -trimprefix Assertion -json -text"; DO NOT EDIT.

package urtypes

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AssertionOperatorName = "EqualsNotEqualsContainsNotContainsGreaterThanLessThanIsNullIsNotNull"

var _AssertionOperatorIndex = [...]uint8{0, 6, 15, 23, 34, 45, 53, 59, 68}

const _AssertionOperatorLowerName = "equalsnotequalscontainsnotcontainsgreaterthanlessthanisnullisnotnull"

func (i AssertionOperator) String() string {
	i -= 1
	if i >= AssertionOperator(len(_AssertionOperatorIndex)-1) {
		return fmt.Sprintf("AssertionOperator(%d)", i+1)
	}
	return _AssertionOperatorName[_AssertionOperatorIndex[i]:_AssertionOperatorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssertionOperatorNoOp() {
	var x [1]struct{}
	_ = x[AssertionEquals-(1)]
	_ = x[AssertionNotEquals-(2)]
	_ = x[AssertionContains-(3)]
	_ = x[AssertionNotContains-(4)]
	_ = x[AssertionGreaterThan-(5)]
	_ = x[AssertionLessThan-(6)]
	_ = x[AssertionIsNull-(7)]
	_ = x[AssertionIsNotNull-(8)]
}

var _AssertionOperatorValues = []AssertionOperator{AssertionEquals, AssertionNotEquals, AssertionContains, AssertionNotContains, AssertionGreaterThan, AssertionLessThan, AssertionIsNull, AssertionIsNotNull}

var _AssertionOperatorNameToValueMap = map[string]AssertionOperator{
	_AssertionOperatorName[0:6]:        AssertionEquals,
	_AssertionOperatorLowerName[0:6]:   AssertionEquals,
	_AssertionOperatorName[6:15]:       AssertionNotEquals,
	_AssertionOperatorLowerName[6:15]:  AssertionNotEquals,
	_AssertionOperatorName[15:23]:      AssertionContains,
	_AssertionOperatorLowerName[15:23]: AssertionContains,
	_AssertionOperatorName[23:34]:      AssertionNotContains,
	_AssertionOperatorLowerName[23:34]: AssertionNotContains,
	_AssertionOperatorName[34:45]:      AssertionGreaterThan,
	_AssertionOperatorLowerName[34:45]: AssertionGreaterThan,
	_AssertionOperatorName[45:53]:      AssertionLessThan,
	_AssertionOperatorLowerName[45:53]: AssertionLessThan,
	_AssertionOperatorName[53:59]:      AssertionIsNull,
	_AssertionOperatorLowerName[53:59]: AssertionIsNull,
	_AssertionOperatorName[59:68]:      AssertionIsNotNull,
	_AssertionOperatorLowerName[59:68]: AssertionIsNotNull,
}

var _AssertionOperatorNames = []string{
	_AssertionOperatorName[0:6],
	_AssertionOperatorName[6:15],
	_AssertionOperatorName[15:23],
	_AssertionOperatorName[23:34],
	_AssertionOperatorName[34:45],
	_AssertionOperatorName[45:53],
	_AssertionOperatorName[53:59],
	_AssertionOperatorName[59:68],
}

// AssertionOperatorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssertionOperatorString(s string) (AssertionOperator, error) {
	if val, ok := _AssertionOperatorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssertionOperatorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssertionOperator values", s)
}

// AssertionOperatorValues returns all values of the enum
func AssertionOperatorValues() []AssertionOperator {
	return _AssertionOperatorValues
}

// AssertionOperatorStrings returns a slice of all String values of the enum
func AssertionOperatorStrings() []string {
	strs := make([]string, len(_AssertionOperatorNames))
	copy(strs, _AssertionOperatorNames)
	return strs
}

// IsAAssertionOperator returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssertionOperator) IsAAssertionOperator() bool {
	for _, v := range _AssertionOperatorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AssertionOperator
func (i AssertionOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AssertionOperator
func (i *AssertionOperator) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AssertionOperator should be a string, got %s", data)
	}

	var err error
	*i, err = AssertionOperatorString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AssertionOperator
func (i AssertionOperator) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AssertionOperator
func (i *AssertionOperator) UnmarshalText(text []byte) error {
	var err error
	*i, err = AssertionOperatorString(string(text))
	return err
}
