// Code generated by "enumer -type AssertionLogic -trimprefix Logic -json -text"; DO NOT EDIT.

package urtypes

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _AssertionLogicName = "ANDOR"

var _AssertionLogicIndex = [...]uint8{0, 3, 5}

const _AssertionLogicLowerName = "andor"

func (i AssertionLogic) String() string {
	i -= 1
	if i >= AssertionLogic(len(_AssertionLogicIndex)-1) {
		return fmt.Sprintf("AssertionLogic(%d)", i+1)
	}
	return _AssertionLogicName[_AssertionLogicIndex[i]:_AssertionLogicIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssertionLogicNoOp() {
	var x [1]struct{}
	_ = x[LogicAND-(1)]
	_ = x[LogicOR-(2)]
}

var _AssertionLogicValues = []AssertionLogic{LogicAND, LogicOR}

var _AssertionLogicNameToValueMap = map[string]AssertionLogic{
	_AssertionLogicName[0:3]:      LogicAND,
	_AssertionLogicLowerName[0:3]: LogicAND,
	_AssertionLogicName[3:5]:      LogicOR,
	_AssertionLogicLowerName[3:5]: LogicOR,
}

var _AssertionLogicNames = []string{
	_AssertionLogicName[0:3],
	_AssertionLogicName[3:5],
}

// AssertionLogicString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssertionLogicString(s string) (AssertionLogic, error) {
	if val, ok := _AssertionLogicNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssertionLogicNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssertionLogic values", s)
}

// AssertionLogicValues returns all values of the enum
func AssertionLogicValues() []AssertionLogic {
	return _AssertionLogicValues
}

// AssertionLogicStrings returns a slice of all String values of the enum
func AssertionLogicStrings() []string {
	strs := make([]string, len(_AssertionLogicNames))
	copy(strs, _AssertionLogicNames)
	return strs
}

// IsAAssertionLogic returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssertionLogic) IsAAssertionLogic() bool {
	for _, v := range _AssertionLogicValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AssertionLogic
func (i AssertionLogic) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AssertionLogic
func (i *AssertionLogic) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AssertionLogic should be a string, got %s", data)
	}

	var err error
	*i, err = AssertionLogicString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AssertionLogic
func (i AssertionLogic) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AssertionLogic
func (i *AssertionLogic) UnmarshalText(text []byte) error {
	var err error
	*i, err = AssertionLogicString(string(text))
	return err
}
